airflow:
  #  extraEnv: |
  #     - name: AIRFLOW__CORE__LOAD_EXAMPLES
  #       value: 'True'
   redis:
    persistence:
      enabled: false
   workers:
    persistence:
      enabled: false
   dags:
    gitSync:
      enabled: true
      # git repo clone url
      # ssh examples ssh://git@github.com/apache/airflow.git
      # git@github.com:apache/airflow.git
      # https example: https://github.com/apache/airflow.git
      repo: https://github.com/ximenesfel/dags.git
      branch: homolog
      subPath: "dags"
